#!/usr/bin/env bash
set +x
RESOURCEGROUP_NAME=$1
CLUSTER_NAME=$2





az aks get-credentials  --resource-group ${RESOURCEGROUP_NAME} --name ${CLUSTER_NAME} --file=./kubeconfig --admin



wget https://github.com/Azure/kubelogin/releases/download/v0.0.9/kubelogin-linux-amd64.zip
unzip kubelogin-linux-amd64.zip
mv bin/linux_amd64/kubelogin /usr/bin
export KUBECONFIG=./kubeconfig
kubelogin convert-kubeconfig -l azurecli