#!/usr/bin/env bash
set +x

export PATH=/root/miniconda3/bin:${PATH}
python ${SYSTEM_DEFAULTWORKINGDIRECTORY}/_idevops_pipeline_libraries/utilities/vault_to_env.py

check_temp_secrets_exists=`ls -lah | grep tmp_secrets | grep -v grep`
if [ -z "${check_temp_secrets_exists}" ]; then
    echo "Temp Secret File Failed To Create"
    ls -lah ./
    exit 1
else
    echo "Temp Secret File Created"
    source ./tmp_secrets
     rm -rf ./tmp_secrets
fi

export DOCKER_HOST="unix:///var/run/docker.sock"
export DOCKER_IMAGE_NAME=${DOCKER_REGISTRY_URL}/${APP_NAME}:${VERSION}
export LIBRARY_PATH=${SYSTEM_DEFAULTWORKINGDIRECTORY}/_idevops_pipeline_libraries
export APPLICATION_PATH=${SYSTEM_DEFAULTWORKINGDIRECTORY}/${RELEASE_PRIMARYARTIFACTSOURCEALIAS}