#!/usr/bin/env bash
set +x

export DOCKER_HOST="unix:///var/run/docker.sock"
export DOCKER_IMAGE_NAME=${DOCKER_REGISTRY_URL}/${APP_NAME}:${VERSION}
export LIBRARY_PATH=${SYSTEM_DEFAULTWORKINGDIRECTORY}/_idevops-automation-depot_cicd-pipeline-automations
export APPLICATION_PATH=${SYSTEM_DEFAULTWORKINGDIRECTORY}/${RELEASE_PRIMARYARTIFACTSOURCEALIAS}