#!/usr/bin/env bash
set +x

keys=$1
echo $keys
from_literal_string=""
for key in $(jq '. | keys | .[]' <<< "$keys"); do
    value=$(jq -r ".[$key]" <<< "$keys");
    echo "$key has value $value"
    key=$(echo $key | tr -d '"')
    from_literal_string="$from_literal_string --from-literal=$key=\"$value\""
done
echo $from_literal_string
kubectl create secret generic $APP_NAME $from_literal_string