#!/usr/bin/env bash
set +x
keys=$1
APP_NAME=$2

from_literal_string=""
for key in $(jq '. | keys | .[]' <<< "$keys"); do
    value=$(jq -r ".[$key]" <<< "$keys");
    key=$(echo $key | tr -d '"')
    from_literal_string="$from_literal_string --from-literal=$key=\"$value\""
done
kubectl create secret generic $APP_NAME $from_literal_string