#!/usr/bin/env bash
set +x

# Start the Docker Daemon
export DOCKER_HOST="unix:///var/run/docker.sock"

cd ${APPLICATION_PATH}

# Build Test and Main Image

docker build -t test .
docker build -t ${DOCKER_IMAGE_NAME} .

# Login to Remote Repository and Push
docker login ${DOCKER_HOST_EXTERNAL} --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
docker push test
cd ${APPLICATION_PATH}
