#!/usr/bin/env bash
set +x

DOCKER_USERNAME=$1
DOCKER_PASSWORD=$2
DOCKER_REGISTRY_URL=$3
#DOCKER_IMAGE_REPOSITORY=$3
APP_NAME=$4
VERSION=$5

echo ${DOCKER_USERNAME}
echo ${DOCKER_PASSWORD}


docker login --username "idevopsio" --password ${DOCKER_PASSWORD} ${DOCKER_REGISTRY_URL}
docker image push local/${APP_NAME}:${VERSION}