#!/usr/bin/env bash
set +x

DOCKER_USERNAME=$1
DOCKER_PASSWORD=$2
DOCKER_REGISTRY_URL=$3
APP_NAME=$4
VERSION=$5

ls
echo "ls above"
docker login --username ${DOCKER_USERNAME} --password ${DOCKER_REGISTRY_URL}
docker image push local/${APP_NAME}:${VERSION}