#!/usr/bin/env bash
set +x
curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh --output Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -ab
export PATH=/root/miniconda3/bin:${PATH}
pip install -r requirements.txt