#!/usr/bin/env bash
set +x

# check to see if jq is already installed
if ! [ -x "$(command -v jq --version)" ]; then
# install if it doesn't
    echo "JQ Doesn't Exist - Install"
    apt-get install -y jq
else
# jq exists
    echo "JQ Exists"
fi