#!/usr/bin/env bash
set +x

# check to see if conda is already installed
check_python_exists=`ls -lah /root | grep miniconda3 | grep -v grep`
if [ -z "${check_python_exists}" ]; then
# install if it does
    echo "Python Doesn't Exist - Install"
    curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh --output Miniconda3-latest-Linux-x86_64.sh
    bash Miniconda3-latest-Linux-x86_64.sh -ab
else
# dont if it doesn't
    echo "Python Exists"
fi
# export path and install requirements
export PATH=/root/miniconda3/bin:${PATH}
pip install -r ${SYSTEM_DEFAULTWORKINGDIRECTORY}/_idevops_pipeline_libraries/requirements.txt