#!/usr/bin/env bash
set +x

APP_NAME=$1
filename=$2
APP_NAMESPACE=$3

ls -d */
echo "where am i"
cd ~/.docker
ls
echo "above APPLICATION PATH"
cd $APPLICATION_PATH

ls -d */
echo "in APPLICATION PATH now"
#kubectl create secret generic regcred \
#  --from-file=.dockerconfigjson=<path/to/.docker/config.json> \
#  --type=kubernetes.io/dockerconfigjson

kubectl apply -n ${APP_NAMESPACE} -f $filename --kubeconfig=../kubeconfig


