#!/usr/bin/env bash
set +x
APP_NAMESPACE=$1
LABEL_KEY=$2
LABEL_VALUE=$3

POD_NAME=$(kubernetes_get_pod_name $2 $3 $APP_NAMESPACE)

kubectl describe pod ${POD_NAME} -n ${APP_NAMESPACE} --kubeconfig=./kubeconfig
