#!/usr/bin/env bash
set +x
APP_NAME=$1
SERVICE_TYPE=$2
APP_NAMESPACE=$3
LABEL_KEY=$4
LABEL_VALUE=$5
PORT=$6
TARGET_PORT=$7

POD_NAME=$(kubernetes_get_pod_name $LABEL_KEY $LABEL_VALUE $APP_NAMESPACE)
echo Name of the Pod: $POD_NAME
kubectl expose pod  $POD_NAME --name $APP_NAME --type=$SERVICE_TYPE --port=$PORT --target-port=$TARGET_PORT -n ${APP_NAMESPACE} --kubeconfig=./kubeconfig