#!/usr/bin/env bash
set +x

APP_NAME=$1
filename=$2
APP_NAMESPACE=$3

kubectl create secret generic regcred \
  --from-file=.dockerconfigjson=<~/.docker/config.json> \
  --type=kubernetes.io/dockerconfigjson

cd $APPLICATION_PATH

ls -d */
echo "in APPLICATION PATH now"


kubectl apply -n ${APP_NAMESPACE} -f $filename --kubeconfig=../kubeconfig


