#!/usr/bin/env bash
set +x

APP_NAME=$1
APP_NAMESPACE=$2
DEPLOYMENT_TYPE=$3

kubectl get events
kubectl rollout status -w $DEPLOYMENT_TYPE/$APP_NAME -n ${APP_NAMESPACE} --kubeconfig=../kubeconfig





