#!/usr/bin/env bash
set +x

APP_NAME=$1
filename=$2
APP_NAMESPACE=$3
secret=$4
key=$5

kubectl delete secret -n ${APP_NAMESPACE} secret-${APP_NAME}-docker

kubectl create secret docker-registry secret-${APP_NAME}-docker \
--$4="$5"
