#!/usr/bin/env bash
set +x

APP_NAME=$1
filename=$2
APP_NAMESPACE=$3

kubectl delete secret -n ${APP_NAMESPACE} secret-${APP_NAME}-docker

kubectl create secret docker-registry secret-${APP_NAME}-docker \
--docker-server=${DOCKER_REGISTRY_URL} \
--docker-username=${DOCKER_USERNAME} \
--docker-password="${DOCKER_PASSWORD}" \
--docker-email=admin@idevops.io
