#!/usr/bin/env bash
set +x

APP_NAME=$1
APP_NAMESPACE=$2
secret=$3
key=$4

kubectl delete secret -n ${APP_NAMESPACE} secret-${APP_NAME}-docker

kubectl create secret docker-registry secret-${APP_NAME}-docker \
--$3="$5"
