#!/usr/bin/env bash
set +x

export PATH=/root/miniconda3/bin:${PATH}

echo "Ensure Sonar is Running."
#sonarstart

echo "Setup Sonar Properties File"
# Required metadata

echo "Scanning Source Directory: ${SYSTEM_DEFAULTWORKINGDIRECTORY}"
echo "sonar.projectKey=org.sonarqube:${APP_NAME}" > sonar-project.properties 
echo "sonar.projectName=${APP_NAME}" >> sonar-project.properties 
echo "sonar.projectVersion=1.0" >> sonar-project.properties 
echo "sonar.language=py" >> sonar-project.properties 
echo "sonar.sourceEncoding=UTF-8" >> sonar-project.properties
echo "sonar.host.url=http://localhost:9000" >> sonar-project.properties
echo "sonar.login=admin" >> sonar-project.properties
echo "sonar.password=admin" >> sonar-project.properties
#echo "sonar.exclusions=html/**, latext/**, za_proxy_report.html" >> sonar-project.properties
echo "sonar.projectBaseDir=${SYSTEM_DEFAULTWORKINGDIRECTORY}" >> sonar-project.properties

echo "Check Sonar Properties"
chmod 777 sonar-project.properties
cat sonar-project.properties




echo $(pwd)

ls -lah


#cp sonar-project.properties ${SYSTEM_DEFAULTWORKINGDIRECTORY}/_idevops-world-of-pew


#echo "Create Project"
#python ${SYSTEM_DEFAULTWORKINGDIRECTORY}/_idevops_pipeline_libraries/sonarqube_create_project.py




echo "Execute Scan, please ensure sonar-project.properties is set properly."
#relies on sonar-project.properties in root project folder
echo $(pwd)
docker run -t --network=host -v $(pwd):/root/src/ zaquestion/sonarqube-scanner ls /root/ ls /root/src/ ls /root/src/_idevops-world-of-pew ls /root/src/_idevops_pipeline_libraries

#echo "Parse and Display Issues from Sonar Cuber Report"
#python ${SYSTEM_DEFAULTWORKINGDIRECTORY}/_idevops_pipeline_libraries/check_project_status.py









