#!/usr/bin/env bash
set +x

check_python_exists=`ls -lah /root | grep miniconda3 | grep -v grep`
if [ -z "${check_temp_secrets_exists}" ]; then
    echo "Python Doesn't Exist Install"
    install_conda
    export PATH=/root/miniconda3/bin:${PATH}
else
    echo "Python Exists Export Path"
    export PATH=/root/miniconda3/bin:${PATH}
fi

python ${SYSTEM_DEFAULTWORKINGDIRECTORY}/_idevops_pipeline_libraries/vault_to_env.py

check_temp_secrets_exists=`ls -lah | grep tmp_secrets | grep -v grep`
if [ -z "${check_temp_secrets_exists}" ]; then
    echo "Temp Secret File Failed To Create"
    ls -lah ./
    exit 1
else
    echo "Temp Secret File Created"
    source ./tmp_secrets
    rm -rf ./tmp_secrets
fi

export DOCKER_IMAGE_NAME=${DOCKER_IMAGE_REPOSITORY}/${APP_NAME}:{VERSION}
export LIBRARY_PATH=${SYSTEM_DEFAULTWORKINGDIRECTORY}/_idevops_pipeline_libraries
export APPLICATION_PATH=${SYSTEM_DEFAULTWORKINGDIRECTORY}/_idevops_world_of_pew