#!/usr/bin/env bash
set +x
python vault_to_env.py
check_temp_secrets_exists=`ls -lah | grep tmp_secrets grep -v grep`
if [ -z "${check_temp_secrets_exists}" ]; then
    echo "Temp Secret File Failed To Create"
    ls -lah ./
    exit 1
else
    echo "Temp Secret File Created"
    source ./tmp_secrets
fi
printenv