#!/usr/bin/env bash
set +x

export PATH=/root/miniconda3/bin:${PATH}
python ${SYSTEM_DEFAULTWORKINGDIRECTORY}/_idevops-automation-depot_cicd-pipeline-automations/utilities/vault_variable_replacement.py




