#!/usr/bin/env bash
set +x

# Restarts the specified container. You can add the seconds to wait for stop before killing the container, as a second argument
CONTAINER=$1
TIME=$2

if [ $# -eq 1 ]; then
    docker restart ${CONTAINER}
else
    docker restart -t ${TIME} ${CONTAINER}
fi