#!/usr/bin/env bash
set +x
DOCKER_IMAGE_NAME=$1

# Start the Docker Daemon
export DOCKER_HOST="unix:///var/run/docker.sock"
cd ${APPLICATION_PATH}

# Build Test and Main Image
echo ${DOCKER_IMAGE_NAME}
echo ${DOCKER_IMAGE_NAME}
echo ${DOCKER_IMAGE_NAME}

#docker build -t test .
#docker build -t $DOCKER_IMAGE_NAME .
#cd ${APPLICATION_PATH}
