#!/usr/bin/env bash
set +x
LABEL_KEY=$1
LABEL_VALUE=$2
APP_NAMESPACE=$3

POD_NAME=$(kubectl get pods -l ${LABEL_KEY}=${LABEL_VALUE} -o jsonpath="{.items[0].metadata.name}" -n ${APP_NAMESPACE} --kubeconfig=./kubeconfig)
echo ${POD_NAME}




