#!/usr/bin/env bash
set +x
APP_OR_SERVICE_NAME=$1
PORTFROM=$2
PORTTO=$3
APP_NAMESPACE=$4

kubectl port-forward -n ${APP_NAMESPACE} ${APP_OR_SERVICE_NAME} ${PORTFROM}:${PORTTO} --kubeconfig=./kubeconfig
